# Generated by Django 4.2.1 on 2024-03-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='Lec_no',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='adm_no',
            field=models.CharField(blank=True, default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
    ]
