# Generated by Django 4.2.1 on 2024-03-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_app', '0002_course_course_code_lecturer_lec_no_student_adm_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='accesslevel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
