# Generated by Django 4.2.1 on 2024-03-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_app', '0003_alter_user_accesslevel_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='semister',
        ),
        migrations.AddField(
            model_name='exam',
            name='endsem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='lab',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='midsem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
