# Generated by Django 4.2.1 on 2024-04-04 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gpa_app', '0004_remove_exam_semister_exam_endsem_exam_lab_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
